print('please input your name, age, address, and hobby')
name=str(input())
age=int(input())
address=str(input())
hobby= str(input())
print('hello my name is ' + name)
print('I am ', age , ' years')
print('I live in ' + address)
print('I like to play '+ hobby)
